using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MinAdaBoost
{
    /// <summary>
    /// A interface use for generate a better data structure for training.
    /// It can be generated by Problem.
    /// </summary>
    public interface TrainData
    {
        /// <summary>
        /// number of the sample
        /// </summary>
        int N { get; }
        /// <summary>
        /// vector
        /// </summary>
        int MaxDim { get; }
        /// <summary>
        /// generate TranData by Problem
        /// </summary>
        /// <param name="prob"></param>
        void GenTrainData(Problem prob);
    }
}
